import { ArrowDown, ArrowUp, ChevronLeft, ChevronRight, Eye, Pencil, Plus, Search, Trash2 } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Link, useOutletContext, useParams, useSearchParams } from 'react-router-dom';
import { deleteRecord, getRecords } from '../api/runtime';
import Modal from '../components/Modal';
import Spinner from '../components/Spinner';
import { useToast } from '../components/ToastProvider';
import RuntimeBreadcrumbs from '../components/runtime/RuntimeBreadcrumbs';
import RuntimeValue from '../components/runtime/RuntimeValue';

export default function DynamicRecordListPage() {
    const { application, metadata, refreshRuntime } = useOutletContext();
    const { moduleId } = useParams();
    const workspaceId = application.workspace_id;
    const [params, setParams] = useSearchParams();
    const [search, setSearch] = useState(params.get('search') || '');
    const [result, setResult] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState('');
    const [deleting, setDeleting] = useState(null);
    const [deletingNow, setDeletingNow] = useState(false);
    const notify = useToast();
    const module = metadata.module;

    const query = useMemo(() => {
        const filters = {};
        params.forEach((value, key) => { if (!key.startsWith('filter_') || value === '') return; const name = key.slice(7); if (name.endsWith('_from') || name.endsWith('_to')) { const part = name.endsWith('_from') ? 'from' : 'to'; const field = name.slice(0, -(part.length + 1)); filters[field] = { ...(filters[field] || {}), [part]: value }; } else filters[name] = value; });
        return { search: params.get('search') || '', page: Number(params.get('page') || 1), sort: params.get('sort') || metadata.list_view.default_sort_field, direction: params.get('direction') || metadata.list_view.default_sort_direction, per_page: Number(params.get('per_page') || metadata.list_view.records_per_page), filters };
    }, [params, metadata]);

    useEffect(() => { const timer = setTimeout(() => { const current = params.get('search') || ''; if (search !== current) setParams((old) => { const next = new URLSearchParams(old); search ? next.set('search', search) : next.delete('search'); next.delete('page'); return next; }); }, 400); return () => clearTimeout(timer); }, [search]);
    useEffect(() => { setLoading(true); setError(''); getRecords(workspaceId, application.id, moduleId, query).then(setResult).catch((requestError) => setError(requestError.response?.data?.message || 'Could not load records.')).finally(() => setLoading(false)); }, [workspaceId, application.id, moduleId, query.search, query.page, query.sort, query.direction, query.per_page, JSON.stringify(query.filters)]);

    const updateParam = (key, value) => setParams((old) => { const next = new URLSearchParams(old); value === '' || value === null ? next.delete(key) : next.set(key, value); if (key !== 'page') next.delete('page'); return next; });
    const sortBy = (field) => { const same = query.sort === field.name; setParams((old) => { const next = new URLSearchParams(old); next.set('sort', field.name); next.set('direction', same && query.direction === 'asc' ? 'desc' : 'asc'); next.delete('page'); return next; }); };
    const remove = async () => { setDeletingNow(true); try { await deleteRecord(workspaceId, application.id, moduleId, deleting.id); setDeleting(null); notify(`${module.singular_name} deleted successfully.`); await refreshRuntime(); const refreshed = await getRecords(workspaceId, application.id, moduleId, query); setResult(refreshed); } catch (requestError) { notify(requestError.response?.data?.message || 'Could not delete this record.', 'error'); } finally { setDeletingNow(false); } };
    const title = (record) => record[module.display_field] || `${module.singular_name} #${record.id}`;

    return <div><RuntimeBreadcrumbs application={application} module={module} /><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-brand-700">Records</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-950">{module.name}</h1><p className="mt-2 text-sm text-slate-500">Manage {module.name.toLowerCase()} in {application.name}.</p></div><Link to={`/apps/${application.id}/modules/${module.id}/create`} className="btn-primary"><Plus size={16} /> Add {module.singular_name}</Link></div>
        <div className="mt-7 rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-200 p-4 lg:flex-row lg:items-center"><div className="relative flex-1"><Search size={16} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" /><input type="search" className="field py-2.5 pl-10" placeholder={`Search ${module.name.toLowerCase()}...`} value={search} onChange={(event) => setSearch(event.target.value)} /></div>{metadata.filters.map((field) => <Filter key={field.id} field={field} value={query.filters[field.name] ?? ''} change={(value, part) => updateParam(`filter_${field.name}${part ? `_${part}` : ''}`, value)} />)}<select className="field w-auto py-2.5" value={query.per_page} onChange={(event) => updateParam('per_page', event.target.value)} aria-label="Rows per page"><option value="10">10 rows</option><option value="20">20 rows</option><option value="50">50 rows</option><option value="100">100 rows</option></select></div>
            {loading ? <div className="grid min-h-64 place-items-center"><Spinner className="size-6 text-brand-600" /></div> : error ? <div className="grid min-h-56 place-items-center p-6 text-center"><div><p className="font-semibold text-red-700">Unable to load records</p><p className="mt-1 text-sm text-red-500">{error}</p></div></div> : result.records.length ? <><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead><tr className="border-b border-slate-200 bg-slate-50/70">{metadata.list_fields.map((field) => <th key={field.id} className="px-4 py-3 text-[10px] font-bold uppercase tracking-wider text-slate-500"><button className="inline-flex items-center gap-1 hover:text-slate-900" onClick={() => sortBy(field)}>{field.label}{query.sort === field.name && (query.direction === 'asc' ? <ArrowUp size={12} /> : <ArrowDown size={12} />)}</button></th>)}<th className="px-4 py-3 text-right text-[10px] font-bold uppercase tracking-wider text-slate-500">Actions</th></tr></thead><tbody>{result.records.map((record) => <tr key={record.id} className="border-b border-slate-100 last:border-0 hover:bg-slate-50/60">{metadata.list_fields.map((field) => <td key={field.id} className="max-w-xs px-4 py-3.5 text-sm text-slate-700"><RuntimeValue field={field} value={record[field.name]} compact /></td>)}<td className="px-4 py-3"><div className="flex justify-end gap-1"><Link to={`/apps/${application.id}/modules/${module.id}/${record.id}`} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100 hover:text-slate-800" aria-label={`View ${title(record)}`}><Eye size={15} /></Link><Link to={`/apps/${application.id}/modules/${module.id}/${record.id}/edit`} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100 hover:text-slate-800" aria-label={`Edit ${title(record)}`}><Pencil size={15} /></Link><button className="rounded-lg p-2 text-slate-400 hover:bg-red-50 hover:text-red-600" onClick={() => setDeleting(record)} aria-label={`Delete ${title(record)}`}><Trash2 size={15} /></button></div></td></tr>)}</tbody></table></div><Pagination pagination={result.pagination} setPage={(page) => updateParam('page', page)} /></> : <div className="grid min-h-72 place-items-center p-8 text-center"><div><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-slate-100 text-slate-400"><Search size={22} /></span><h2 className="mt-4 font-bold text-slate-900">{query.search || Object.keys(query.filters).length ? `No matching ${module.name.toLowerCase()}` : `No ${module.name.toLowerCase()} yet`}</h2><p className="mt-2 text-sm text-slate-500">{query.search || Object.keys(query.filters).length ? 'Try adjusting your search or filters.' : `Start by creating your first ${module.singular_name}.`}</p>{!query.search && !Object.keys(query.filters).length && <Link to={`/apps/${application.id}/modules/${module.id}/create`} className="btn-primary mt-5"><Plus size={16} /> Add {module.singular_name}</Link>}</div></div>}
        </div>
        <Modal open={Boolean(deleting)} onClose={deletingNow ? () => {} : () => setDeleting(null)} title={`Delete this ${module.singular_name}?`} description="This record will be permanently deleted."><div className="p-6"><p className="rounded-xl border border-red-100 bg-red-50 p-4 text-sm text-red-700">You are deleting <strong>{deleting ? title(deleting) : ''}</strong>. This cannot be undone.</p><div className="mt-6 flex justify-end gap-3"><button className="btn-secondary" onClick={() => setDeleting(null)} disabled={deletingNow}>Cancel</button><button className="inline-flex items-center gap-2 rounded-xl bg-red-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60" onClick={remove} disabled={deletingNow}>{deletingNow ? <Spinner /> : <Trash2 size={16} />} Delete</button></div></div></Modal>
    </div>;
}

function Filter({ field, value, change }) { if (['select', 'radio'].includes(field.field_type)) return <select className="field w-auto min-w-36 py-2.5" value={value} onChange={(event) => change(event.target.value)}><option value="">All {field.label}</option>{field.options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select>; if (['checkbox', 'toggle'].includes(field.field_type)) return <select className="field w-auto min-w-32 py-2.5" value={value} onChange={(event) => change(event.target.value)}><option value="">All {field.label}</option><option value="1">Yes</option><option value="0">No</option></select>; if (field.field_type === 'date') return <div className="flex gap-2"><input type="date" className="field w-auto py-2.5" value={value?.from || ''} onChange={(event) => change(event.target.value, 'from')} aria-label={`${field.label} from`} /><input type="date" className="field w-auto py-2.5" value={value?.to || ''} onChange={(event) => change(event.target.value, 'to')} aria-label={`${field.label} to`} /></div>; return null; }
function Pagination({ pagination, setPage }) { return <div className="flex flex-col items-center justify-between gap-3 border-t border-slate-200 px-4 py-3 sm:flex-row"><p className="text-xs text-slate-400">Showing {pagination.from || 0}–{pagination.to || 0} of {pagination.total}</p><div className="flex items-center gap-2"><button className="btn-secondary px-3 py-2" disabled={pagination.current_page <= 1} onClick={() => setPage(pagination.current_page - 1)}><ChevronLeft size={15} /></button><span className="text-xs font-semibold text-slate-600">Page {pagination.current_page} of {pagination.last_page}</span><button className="btn-secondary px-3 py-2" disabled={pagination.current_page >= pagination.last_page} onClick={() => setPage(pagination.current_page + 1)}><ChevronRight size={15} /></button></div></div>; }
