import { ArrowDown, ArrowUp, ListChecks, Save } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { useOutletContext, useParams } from 'react-router-dom';
import { getListView, saveListView } from '../api/runtime';
import Spinner from '../components/Spinner';
import { useToast } from '../components/ToastProvider';

export default function ListViewBuilderPage() {
    const { module } = useOutletContext();
    const { workspaceId, applicationId, moduleId } = useParams();
    const [view, setView] = useState(null); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const notify = useToast();
    useEffect(() => { getListView(workspaceId, applicationId, moduleId).then(setView).catch((requestError) => setError(requestError.response?.data?.message || 'Could not load list settings.')); }, [workspaceId, applicationId, moduleId]);
    const visible = useMemo(() => view?.columns.filter((column) => column.visible) || [], [view]);
    const toggle = (fieldId) => setView((current) => ({ ...current, columns: current.columns.map((column) => column.field_id === fieldId ? { ...column, visible: !column.visible } : column) }));
    const move = (fieldId, direction) => setView((current) => { const columns = [...current.columns]; const index = columns.findIndex((column) => column.field_id === fieldId); const target = index + direction; if (target < 0 || target >= columns.length) return current; [columns[index], columns[target]] = [columns[target], columns[index]]; return { ...current, columns }; });
    const save = async () => { setSaving(true); try { const saved = await saveListView(workspaceId, applicationId, moduleId, { ...view, columns: view.columns.map((column, index) => ({ field_id: column.field_id, visible: column.visible, sort_order: index + 1 })) }); setView(saved); notify('List view saved successfully.'); } catch (requestError) { notify(requestError.response?.data?.message || 'Could not save list settings.', 'error'); } finally { setSaving(false); } };
    if (!view && !error) return <div className="grid min-h-96 place-items-center"><Spinner className="size-7 text-brand-600" /></div>;
    if (error) return <div className="rounded-xl border border-red-100 bg-red-50 p-5 text-sm text-red-700">{error}</div>;
    return <div><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-brand-700">Runtime table</p><h2 className="mt-2 text-2xl font-bold text-slate-950">{module.name} list view</h2><p className="mt-2 text-sm text-slate-500">Choose and order the columns users see in the generated admin.</p></div><button className="btn-primary" onClick={save} disabled={saving}>{saving ? <Spinner /> : <Save size={16} />} Save List View</button></div>
        <div className="mt-7 grid gap-5 xl:grid-cols-[1fr_.8fr]"><section className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="font-bold text-slate-900">List columns</h3><p className="mt-1 text-xs text-slate-400">Select up to the fields that make this module easy to scan.</p><div className="mt-5 space-y-2">{view.columns.map((column, index) => <div key={column.field_id} className={`flex items-center gap-3 rounded-xl border p-3 ${column.visible ? 'border-brand-200 bg-brand-50/50' : 'border-slate-200'}`}><input type="checkbox" checked={column.visible} onChange={() => toggle(column.field_id)} className="size-4 accent-brand-600" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-slate-800">{column.label}</p><p className="text-[10px] uppercase text-slate-400">{column.field_type}</p></div><button onClick={() => move(column.field_id, -1)} disabled={index === 0} className="rounded-lg border border-slate-200 bg-white p-2 text-slate-400 disabled:opacity-30"><ArrowUp size={13} /></button><button onClick={() => move(column.field_id, 1)} disabled={index === view.columns.length - 1} className="rounded-lg border border-slate-200 bg-white p-2 text-slate-400 disabled:opacity-30"><ArrowDown size={13} /></button></div>)}</div></section>
            <div className="space-y-5"><section className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="font-bold text-slate-900">Defaults</h3><div className="mt-4 space-y-4"><Setting label="Default sort field"><select className="field" value={view.default_sort_field} onChange={(event) => setView({ ...view, default_sort_field: event.target.value })}><option value="created_at">Created At</option><option value="updated_at">Updated At</option>{visible.map((column) => <option key={column.field_id} value={column.name}>{column.label}</option>)}</select></Setting><Setting label="Direction"><select className="field" value={view.default_sort_direction} onChange={(event) => setView({ ...view, default_sort_direction: event.target.value })}><option value="desc">Newest / highest first</option><option value="asc">Oldest / lowest first</option></select></Setting><Setting label="Rows per page"><select className="field" value={view.records_per_page} onChange={(event) => setView({ ...view, records_per_page: Number(event.target.value) })}><option value="10">10</option><option value="20">20</option><option value="50">50</option><option value="100">100</option></select></Setting></div></section><section className="rounded-2xl border border-slate-200 bg-slate-950 p-5 text-white"><div className="flex items-center gap-2"><ListChecks size={17} className="text-brand-400" /><h3 className="font-bold">Preview</h3></div><div className="mt-4 overflow-x-auto rounded-xl border border-white/10"><div className="flex min-w-max">{visible.length ? visible.map((column) => <span key={column.field_id} className="min-w-32 border-r border-white/10 px-3 py-3 text-[10px] font-bold uppercase tracking-wider text-slate-300 last:border-0">{column.label}</span>) : <span className="px-4 py-4 text-xs text-slate-400">Select at least one column.</span>}</div></div></section></div></div>
    </div>;
}
function Setting({ label, children }) { return <label className="block"><span className="mb-1.5 block text-xs font-semibold text-slate-600">{label}</span>{children}</label>; }
