import { Save, Settings } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useOutletContext, useParams } from 'react-router-dom';
import { getFields } from '../api/fields';
import { updateModule } from '../api/modules';
import Spinner from '../components/Spinner';
import { useToast } from '../components/ToastProvider';

export default function ModuleSettingsPage() {
    const { module } = useOutletContext(); const { workspaceId, applicationId, moduleId } = useParams(); const notify = useToast();
    const [fields, setFields] = useState([]); const [form, setForm] = useState({ name: module.name, singular_name: module.singular_name || '', description: module.description || '', icon: module.icon || 'database', status: module.status, display_field_id: module.display_field_id || '' }); const [saving, setSaving] = useState(false);
    useEffect(() => { getFields(workspaceId, applicationId, moduleId).then((items) => setFields(items.filter((field) => field.status === 'active' && !field.is_hidden && field.field_type !== 'password'))); }, [workspaceId, applicationId, moduleId]);
    const save = async (event) => { event.preventDefault(); setSaving(true); try { const updated = await updateModule(workspaceId, applicationId, moduleId, { ...form, display_field_id: form.display_field_id ? Number(form.display_field_id) : null }); setForm({ ...form, ...updated, display_field_id: updated.display_field_id || '' }); notify('Module settings saved successfully.'); } catch (requestError) { notify(requestError.response?.data?.message || 'Could not save module settings.', 'error'); } finally { setSaving(false); } };
    return <div><div><p className="text-xs font-bold uppercase tracking-[.14em] text-brand-700">Configuration</p><h2 className="mt-2 text-2xl font-bold text-slate-950">Module settings</h2><p className="mt-2 text-sm text-slate-500">Control the human-facing names and runtime behavior without changing stable internal identifiers.</p></div><form onSubmit={save} className="mt-7 max-w-2xl rounded-2xl border border-slate-200 bg-white p-5 sm:p-7"><div className="mb-6 flex items-center gap-3 border-b border-slate-100 pb-5"><span className="grid size-10 place-items-center rounded-xl bg-brand-50 text-brand-700"><Settings size={18} /></span><div><h3 className="font-bold text-slate-900">General</h3><p className="text-xs text-slate-400">Shown throughout builder and runtime screens.</p></div></div><div className="grid gap-5 sm:grid-cols-2"><Setting label="Module name"><input className="field" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required maxLength="100" /></Setting><Setting label="Singular name"><input className="field" value={form.singular_name} onChange={(event) => setForm({ ...form, singular_name: event.target.value })} placeholder="Product" maxLength="100" /></Setting><Setting label="Icon"><input className="field" value={form.icon} onChange={(event) => setForm({ ...form, icon: event.target.value })} maxLength="50" /></Setting><Setting label="Status"><select className="field" value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })}><option value="active">Active</option><option value="inactive">Inactive</option></select></Setting><div className="sm:col-span-2"><Setting label="Record display field"><select className="field" value={form.display_field_id} onChange={(event) => setForm({ ...form, display_field_id: event.target.value })}><option value="">Automatic (first suitable text field)</option>{fields.map((field) => <option key={field.id} value={field.id}>{field.label}</option>)}</select></Setting><p className="mt-1.5 text-xs text-slate-400">Used in record titles, breadcrumbs, and delete confirmations.</p></div><div className="sm:col-span-2"><Setting label="Description"><textarea className="field" rows="4" value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} maxLength="1000" /></Setting></div></div><div className="mt-7 flex justify-end border-t border-slate-100 pt-6"><button className="btn-primary" disabled={saving}>{saving ? <Spinner /> : <Save size={16} />} Save settings</button></div></form></div>;
}
function Setting({ label, children }) { return <label className="block"><span className="mb-1.5 block text-xs font-semibold text-slate-600">{label}</span>{children}</label>; }
